### ISSUE TITLE
How to persist data on the datanodes?

### ISSUE THREAD

**Issue by frol** [elek/docker-hadoop#3]
It seems that the example config persists only the namenode data to the host volume (at least, I see only the `./namenode/` folder in the mounted volume after I start namenode and datanode). What is the point of `/tmp:/data` volume mounting for the datanode container in this case? How can I specify the data root folder to be `/data/datanode`? (Given the logs I see, the default datanode folder is `/tmp/hadoop-root/dfs/`)

*P.S. Thank you for building these nice BigData images!*

**Comment by frol** [comment]
Currently, I just mount host volume to `/tmp/hadoop-root/dfs/data` and it seems to work.

**Comment by OneCricketeer** [comment]
The default datanode directory is `/tmp/hadoop-${user.name}/dfs/data` - user here being root running the datanode process.

Worth mentioning that the namenode directory also needs persisted to maintain the metadata of the datanodes

**Comment by skonmeme** [comment]
If you want to save data in volume, use following an environmental variable:
HDFS-SITE.XML_dfs.datanode.data.dir="/data"
